# .github/workflows/publish-docs.yml
name: Publish API Docs
on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: apinotes/validate-action@v1
        with:
          api-key: apn_dbbf73a9955819d3cda4d523f6709bbc746bb737
          spec-path: openapi-full-example-v2.5.1.json          # path to your spec in the repo
          project-id: 6a9ec79100450c60b47125b9