# .github/workflows/publish-docs.yml
name: Publish API Docs
on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: apinotes/openapi-validate@v1.1.0
        with:
          api-key: apn_00494c013c731a119820a5aa5d7b1e8c9777340f
          spec-path: openapi-full-example-v3.0.0.json          # path to your spec in the repo
          project-id: 6aa3f813ee6c177a728b9a56
